export {default as Home} from "./home"
export {default as Technologies} from "./technologies"
export {default as About} from "./about"
export {default as Projects} from "./projects"
export {default as Test} from "./test"
// export {default as Contact} from "./contact"
